sudo: required
dist: trusty
language: cpp

cache:
  directories:
    - deps

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
      env:
        - CONFIG=debug_x64
        - CONFDIR=Debug
        - COMPILER=gcc
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
      env:
        - CONFIG=release_x64
        - CONFDIR=Release
        - COMPILER=gcc

before_install:
  - export CC=gcc-5
  - export CXX=g++-5
  - sudo apt-get update -qq
  - sudo apt-get install -y unzip openjdk-7-jdk git uuid-dev valgrind
  - bash ./install-travis-deps.sh

before_script:
  - cp environment.travis.lua environment.lua
  - premake5 gmake
  - make config=$CONFIG all

script:
  - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(pwd)/deps/antlr4/runtime/Cpp/dist" valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes ./bin/$CONFDIR/testimq
